apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 10Gi